using System.Diagnostics.CodeAnalysis;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace project_euler
{
	public static class Functions
	{
		///////// Problem 1 //////////
		// If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
		// Find the sum of all the multiples of 3 or 5 below the provided parameter value number.

		/// <summary>
		/// Calculates the sum of all natural numbers less than the specified number that are multiples of 3 or 5.
		/// </summary>
		/// <param name="number">Exclusive upper bound; natural numbers less than number are considered.</param>
		/// <returns>The sum of all multiples of 3 or 5 that are less than number.</returns>
		public static uint MultiplesOf3And5(uint number)
		{
			if (number == 0) return 0;

			return MultiplesOfXAndY(number, 3, 5);
		}

		/// <summary>
		/// Count integers strictly less than limit that are multiples of x or y using inclusion–exclusion.
		/// </summary>
		/// <remarks>The method decrements limit before computation; calling with limit == 0 wraps to uint.MaxValue.
		/// Uses x * y for the intersection rather than the least common multiple, so results may be incorrect when x and y
		/// are not coprime. Multiplication of x and y can overflow; inputs are not validated.</remarks>
		/// <param name="limit">Upper exclusive bound; only values strictly less than limit are considered.</param>
		/// <param name="x">First divisor used to count multiples.</param>
		/// <param name="y">Second divisor used to count multiples.</param>
		/// <returns>The number of integers less than limit that are divisible by x or y.</returns>
		public static uint MultiplesOfXAndY(uint limit, uint x, uint y)
		{
			limit--;

			return MultiplesOfX(limit, x) +
				MultiplesOfX(limit, y) -
				MultiplesOfX(limit, x * y);
		}

		private static uint MultiplesOfX(uint limit, uint divisor)
		{
			uint count = limit / divisor;
			return divisor * count * (count + 1) / 2;
		}


		///////// Problem 2 //////////
		// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
		// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
		// By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

		/// <summary>
		/// Computes the sum of even-valued Fibonacci numbers that do not exceed the specified maximum.
		/// </summary>
		/// <remarks>Returns 0 when number is less than or equal to 1.</remarks>
		/// <param name="number">The inclusive upper bound for Fibonacci terms to include in the sum.</param>
		/// <returns>The sum of even-valued Fibonacci numbers less than or equal to number.</returns>
		public static uint FiboEvenSum(uint number)
		{
			if (number <= 1) return 0;

			return SumEvenFiboNumbers(1u, 2u, number, 2);
		}

		private static uint SumEvenFiboNumbers(uint previousNum, uint currentNum, uint fiboLimit, uint sumOfEvenFiboNumbers)
		{
			var sumOfPrevTwoNumbers = previousNum + currentNum;

			if (sumOfPrevTwoNumbers > fiboLimit)
				return sumOfEvenFiboNumbers;
			else
			{
				uint sumOfEvenFiboNumbers_Updated = sumOfEvenFiboNumbers;
				if (sumOfPrevTwoNumbers % 2 == 0) sumOfEvenFiboNumbers_Updated += sumOfPrevTwoNumbers;
				return SumEvenFiboNumbers(currentNum, sumOfPrevTwoNumbers, fiboLimit, sumOfEvenFiboNumbers_Updated);
			}
		}

		///////// Problem 3 //////////
		// The prime factors of 13195 are 5, 7, 13 and 29.
		// What is the largest prime factor of the given number?

		public static uint LargestPrimeFactor(long number)
		{
			return 0;
		}
	}
}
